name: Code analyzing on pull request

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]
jobs:
  run-linter:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run lint

  run-build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm ci
      - name: Create config file
        run: echo 'export const firebaseConfig = { ${{secrets.CONFIG}} }' > firebase.config.ts
      - run: npm run build

