name: GitHub Actions

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]
jobs:
  run-linter:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  run-build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Create congif file
        run: echo 'export const firebaseConfig = { apiKey' > h.ts | cat h.ts

